<?php
/**
 * Product list
 *
 * @category   Manu
 * @package    Manu_Saleproducts
 * @author    Manu Jose K
 */

class Manu_Saleproducts_Model_Observer {
        /*
         * Cron job for every day.
         * Functionality:Remove all products from Sale category when special price date ends.
         * Notification:send mail to the store owner with list of removed products.
         * 
         */

        public function removeOfferProducts()
        {

                $mailContent = array();
                $sales;
                $i = 0;
                $categories = Mage::getModel('catalog/category')->getCollection()
                        ->addAttributeToFilter('name', Mage::getStoreConfig('sale_category/general/offer_category'))
                        ->addAttributeToSelect('id')
                        ->load();
                foreach ($categories as $product)
                { //loop for getting products
                        $sales[$i] = $product->getId();
                        $i++;
                }
                $categoryCollection = Mage::getModel('catalog/category')->getCollection()
                        ->addAttributeToSelect('id')
                        ->load();
                foreach ($categoryCollection as $cat):

                        $currentCategoryId = $cat->getId();
                        if (in_array($currentCategoryId, $sales))
                        {
                                $todayDate = date('m/d/y');
                                $yesterday = mktime(0, 0, 0, date('m'), date('d') - 1, date('y'));
                                $yesterdayDate = date('m/d/y', $yesterday);
                                $catagoryModel = Mage::getModel('catalog/category')->load($currentCategoryId);
                                $productCollection = Mage::getResourceModel('catalog/product_collection')->addAttributeToSelect('name')->addCategoryFilter($catagoryModel);
                                $productCollection->addAttributeToFilter('special_to_date', array('date' => true, 'to' => $yesterdayDate));
                                $currentStoreID = Mage::app()->getStore()->getId();
                                Mage::app()->setCurrentStore(Mage_Core_Model_App::ADMIN_STORE_ID);
                                foreach ($productCollection as $currentProduct)
                                {
                                        array_push($mailContent, $currentProduct->getName());
                                        $categoryIds = $currentProduct->getCategoryIds();
                                        $categoryIds = str_replace($currentCategoryId, "", $categoryIds);
                                        $currentProduct->setCategoryIds($categoryIds);
                                        $currentProduct->save();
                                }
                                Mage::app()->setCurrentStore($currentStoreID);
                        }

                endforeach;
                if (Mage::getStoreConfig('sale_category/general/offer_mail'))
                {
                        $newContent = "Following products are removed from Sale/Offer Category due to the end of special price date.\r\n
                                This mail was generated by a cron job.<br/> You can turn of this mail notification in system->config->catalog->Sale / Offer";
                        $headers = "MIME-Version: 1.0" . "\r\n";
                        $headers .= "Content-type:text/html;charset=iso-8859-1" . "\r\n";
                        $headers .= 'From: <' . Mage::getStoreConfig('general/store_information/name') . '@magento.com>';
                        $mailContent = array_unique($mailContent);
                        foreach ($mailContent as $value)
                        {
                                $newContent = $newContent . "\r\n" . $value;
                        }
                        mail(Mage::getStoreConfig('trans_email/ident_general/email'), "Removed Products", $newContent, $headers);
                }
                $this->saleProductsImport(TRUE);
        }

        public function saleProductsImport($cron=null)
        {
                if (Mage::getStoreConfig('sale_category/general/offer_cron') || isset($cron))
                {
                        $mailContent = array();
                        $categories = Mage::getModel('catalog/category')->getCollection()
                                ->addAttributeToSelect('id')
                                ->addAttributeToSelect('name')
                                ->addAttributeToFilter('is_active', array('eq' => true))
                                ->addAttributeToFilter('level', array('eq' => '1'))
                                ->load();
                        echo '<pre/>';
                        foreach ($categories as $value)
                        {
                                $categoriesColl = Mage::getModel('catalog/category')->getCollection()
                                        ->addAttributeToFilter('name', Mage::getStoreConfig('sale_category/general/offer_category'))
                                        ->addAttributeToSelect('id')
                                        ->addAttributeToSelect('name')
                                        ->load($value['id']);
                        }
                        foreach ($categoriesColl as $value)
                        {
                                echo $value['entity_id'];
                                $todayDate = date('m/d/y');
                                $productCollection = Mage::getResourceModel('catalog/product_collection')->addAttributeToSelect('name');
                                $productCollection->addAttributeToFilter('special_from_date', array('date' => true, 'from' => $todayDate));
                                foreach ($productCollection as $currentProduct)
                                {

                                        $categoryIds = $currentProduct->getCategoryIds();
                                        if (!in_array($value['entity_id'], $categoryIds))
                                        {
                                                echo "already in array";
                                                array_push($categoryIds, $value['entity_id']);
                                                array_push($mailContent, $currentProduct->getName());
                                        }
                                        $currentProduct->setCategoryIds($categoryIds);
                                        $currentProduct->save();
                                        print_r($categoryIds);
                                        echo $currentProduct['name'];
                                }
                                echo '<br/>hiiii<br/>';
                        }
                        if (Mage::getStoreConfig('sale_category/general/offer_mail'))
                        {
                                $newContent = "Following products are Added to Sale/Offer Category  by a cron job.<br/> You can turn of this mail notification in system->config->catalog->Sale / Offer\r\n";
                                $headers = "MIME-Version: 1.0" . "\r\n";
                                $headers .= "Content-type:text/html;charset=iso-8859-1" . "\r\n";
                                $headers .= 'From: <' . Mage::getStoreConfig('general/store_information/name') . '@magento.com>';
                                $mailContent = array_unique($mailContent);
                                foreach ($mailContent as $value)
                                {
                                        $newContent = $newContent . "\r\n" . $value;
                                }
                                mail(Mage::getStoreConfig('trans_email/ident_general/email'), "Product Added to offer Category", $newContent, $headers);
                        }
                }
        }

}

?>
